# Generated by Django 5.0.2 on 2024-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addCategory', '0001_initial'),
        ('addTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='category',
            field=models.ManyToManyField(to='addCategory.addcategory'),
        ),
    ]
